---
- hosts: webservers
  step:
        - apt-get update && apt-get -qq install git-ftp ssh
        - ssh -p 22 -i ~/home/admin/.ssh/id_rsa $admin@${hosts} "touch test"
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "nginx"
        state: "present"
    - name: Start Nginx Server
      service:
        name: nginx
        state: started
        enable: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /usr/share/nginx/html/
...
